# Source oh-my-zsh if it is installed.
if [[ -d $HOME/.oh-my-zsh ]]; then
  # Path to your oh-my-zsh configuration.
  ZSH=$HOME/.oh-my-zsh

  # Set name of the theme to load.
  ZSH_THEME="robbyrussell"

  # Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
  # Example format: plugins=(rails git textmate ruby lighthouse)
  plugins=(git ruby rails autojump)

  # Load default oh-my-zsh stuff
  source $ZSH/oh-my-zsh.sh
fi

# Don't change. The following determines where YADR is installed.
yadr=`find -L ~ -type file -maxdepth 2 -name .yadr | head | sed 's:\.yadr\/::'`

# Configuration
source $yadr/zsh/aliases
source $yadr/zsh/zsh_aliases

# Things I don't want to publish to github
[[ -s "$HOME/.secrets" ]] && source "$HOME/.secrets"

# Vim mode
bindkey -v

# Give me my bash style incremental search
bindkey '^R' history-incremental-search-backward

# Speed up git completion
# http://talkings.org/post/5236392664/zsh-and-slow-git-completion
__git_files () {
  _wanted files expl 'local files' _files
}

# Always pushd when changing directory
setopt auto_pushd

# Fuzzy matching of completions for when you mistype them:
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

# RVM
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Add path to our custom bins
# Customize to your needs...
#export ARCHFLAGS="-arch x86_64"
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/usr/local/mysql/lib/"

export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/texbin:/usr/local/mysql/bin:/Users/pietia/Downloads/MacVim-snapshot-64/MacVim.app/Contents/MacOS/
export PATH=$PATH:$yadr/bin:$yadr/bin/yadr
#export PATH="$HOME/.rbenv/bin:$PATH"

export LANG=en_AU.UTF-8
eval "$(rbenv init -)"

